version: '3'
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_USER=$DB_USER
    ports:
      - 3306:3306
    volumes:
      - ./src/database/migrations:/docker-entrypoint-initdb.d:ro
  app:
    build: ./
    ports:
      - 6111:6111
      - 6112:6112
    volumes:
      - ./:/home/node/app